"""add_sent_colum_at_forward_msg

Revision ID: 13ed45017dd9
Revises: a9ae85ea3ba9
Create Date: 2025-02-28 14:53:14.509851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ed45017dd9'
down_revision: Union[str, None] = 'a9ae85ea3ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forwarded_messages', sa.Column('sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forwarded_messages', 'sent')
    # ### end Alembic commands ###
