"""add_first_name column

Revision ID: 3329dd47776a
Revises: c4bebe41ddf3
Create Date: 2025-03-01 15:14:43.161739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3329dd47776a'
down_revision: Union[str, None] = 'c4bebe41ddf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
