"""delete colum reciv_init_msg from user

Revision ID: 8bf4ed1be11d
Revises: 6e7420f06b11
Create Date: 2025-03-01 07:51:05.006970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf4ed1be11d'
down_revision: Union[str, None] = '6e7420f06b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_received_initial_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_received_initial_messages', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
