"""set that promo.. and endat can be nullable

Revision ID: 91cd43af728c
Revises: 8bf4ed1be11d
Create Date: 2025-03-01 08:46:07.457088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91cd43af728c'
down_revision: Union[str, None] = '8bf4ed1be11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'promo_code',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'subscription_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscription_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'promo_code',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
