"""add_lang_code_to_user_schema

Revision ID: ee535f5612a2
Revises: 0320d685662b
Create Date: 2025-03-17 19:35:04.176684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee535f5612a2'
down_revision: Union[str, None] = '0320d685662b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forwarded_message_errors', sa.Column('message_id', sa.Integer(), nullable=False))
    op.add_column('forwarded_message_errors', sa.Column('error_text', sa.String(), nullable=False))
    op.drop_constraint('forwarded_message_errors_forward_message_id_key', 'forwarded_message_errors', type_='unique')
    op.create_unique_constraint(None, 'forwarded_message_errors', ['message_id'])
    op.drop_constraint('forwarded_message_errors_forward_message_id_fkey', 'forwarded_message_errors', type_='foreignkey')
    op.create_foreign_key(None, 'forwarded_message_errors', 'forwarded_messages', ['message_id'], ['id'])
    op.drop_column('forwarded_message_errors', 'forward_message_error_text')
    op.drop_column('forwarded_message_errors', 'forward_message_id')
    op.add_column('users', sa.Column('language_code', sa.String(), nullable=False,server_default='ru'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_code')
    op.add_column('forwarded_message_errors', sa.Column('forward_message_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('forwarded_message_errors', sa.Column('forward_message_error_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'forwarded_message_errors', type_='foreignkey')
    op.create_foreign_key('forwarded_message_errors_forward_message_id_fkey', 'forwarded_message_errors', 'forwarded_messages', ['forward_message_id'], ['id'])
    op.drop_constraint(None, 'forwarded_message_errors', type_='unique')
    op.create_unique_constraint('forwarded_message_errors_forward_message_id_key', 'forwarded_message_errors', ['forward_message_id'])
    op.drop_column('forwarded_message_errors', 'error_text')
    op.drop_column('forwarded_message_errors', 'message_id')
    # ### end Alembic commands ###
